### ISSUE TITLE
undefined method `constantize' for #<ActiveModel::Name

### ISSUE THREAD

**Issue by rchady** [fatfreecrm/fat_free_crm#484] opened 2016-03-28 17:29 UTC
Trying to create a search and I'm getting the error:

```
ActionView::Template::Error (undefined method `constantize' for #<ActiveModel::Name:0x00000004c85420>):
    4:   <%= javascript_tag do %>
    5:     if (window.Ransack == null) { window.Ransack = {}; }
    6:     Ransack.alt_predicates_i18n = <%= I18n.translate(:"ransack.predicates.alt", :default => {}).to_json.html_safe %>;
    7:     Ransack.value_field_labels  = <%= f.labels_for_value_fields.to_json.html_safe %>
    8:   <% end %>
    9:
   10:   <div class="row">
  app/views/entities/_search.html.haml:16:in `_app_views_entities__search_html_haml___3032588275568370446_48025820'
  app/views/opportunities/index.html.haml:7:in `_app_views_opportunities_index_html_haml___1509649107143017558_70179435086900'
  app/controllers/entities/opportunities_controller.rb:16:in `index'
```

This seems to come out of the ransack_ui gem as far as I can tell.

**Comment by steveyken** [comment] 2016-03-29 04:19
Thanks for reporting. Seems to be related to https://github.com/ndbroadbent/ransack_ui/issues/7 as you noted. What steps did you take to reproduce on FFCRM?

**Comment by rchady** [comment] 2016-03-29 11:10
Fresh install of FFCRM, created a personal list, saved it... and BOOM!  It seems to do the save, because the list entry shows up, but clicking on it any time will hit the error.

**Comment by rchady** [comment] 2016-04-07 11:51
Is there any update on this?  Or a workaround I could do for now?  I dug in to ransack_ui but did not see any obvious place where #constantize was being called on the wrong thing.

**Comment by stanleylhs** [comment] 2016-09-01 08:02
@rchady I can't reproduce this error from the current master branch.

Here are my steps:
Do an advance search, save it in My Lists, then click on the newly created list.

Is this the right steps to reproduce the error?

**Comment by johnnyshields** [comment] 2018-01-06 07:27
@rchady can you confirm if the issue persists on latest master? Otherwise we'll close it.

**Comment by johnnyshields** [comment] 2018-01-06 09:36
Please reopen if issue persists.

**Closed by johnnyshields** 2018-01-06 09:36 UTC
