### ISSUE TITLE
Using demo data with one contact having Do Not Call = true, search fails

### ISSUE THREAD

**Issue by woo37830** [fatfreecrm/fat_free_crm#828] opened 2019-08-22 16:31 UTC
I loaded the demo data and then set one contact to have do not call = true and who has a phone number.  I then under the contact tab, did and advance search for contacts with do not call = true and get all contacts instead of just the one(?)

**Comment by johnbumgardner** [comment] 2023-05-26 20:53
![image](https://github.com/fatfreecrm/fat_free_crm/assets/38589044/5004ff8e-6b72-4f9c-9365-15ef4f4ca373)
![image](https://github.com/fatfreecrm/fat_free_crm/assets/38589044/4343613c-366f-4e6a-b958-34731fc1a5f6)

Hey I am unable to reproduce this issue. Going to close this out.

**Closed by johnbumgardner** 2023-05-26 20:53 UTC
Labels: Bug
